---
title: "Data Preparation"
author: "Dana Melamed"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_chunk$set(eval = FALSE)
library(swnsmodelr)
```
### Stations Spatial Object

```{r}
stations_info_df.1 <- read.csv('f:\\WeatherData\\NSWeatherStns.csv')
stations_info_df.2 <- stations_info_df.1 %>% dplyr::select(stationid = StnID,
                                                       NORTHING = Northing, 
                                                       EASTING = Easting,
                                                       type = StnType) %>%
                   filter(EASTING < 4000000)


temperatures_df.1 <- read.csv('f:\\WeatherData\\daily_20110101_20180218.csv')
temperatures_df.2 <- temperatures_df.1 %>% dplyr::select(date_time,
                                                 stationid,
                                                 temp_min,
                                                 temp_max)

```

```{r}

# coordinates(stations_sp) = ~ EASTING + NORTHING
# plot(stations_sp)
rasters_list <- create_rasters_list('f:\\data\\rasters\\input_rasters',
                                     c('dem','cp','east','north','tpi5000m','asp','slp'),
                                     resolution = '500m')
rasters_brick <- brick(rasters_list)
names(rasters_brick) <-  c('dem','cp','east','north','tpi5000m','asp','slp')

join_df <- dplyr::right_join(temperatures_df.2,
                                stations_info_df.2,
                                by = 'stationid') %>%
  filter(!is.na(EASTING))

# Calculate daily mean temperature, GDD10, and total GDD10 (Apr-Nov)
stations_df.1 <- join_df %>%
  mutate(temp_mean = (temp_min + temp_max)/2) %>%
  filter(between(month(date_time),4,11)) %>% 
  filter(stationid!='S40')
  
# use only swns stations
swns_raster <- raster('f:\\data\\swns.tif')
names(swns_raster) <- 'swns'
```

```{r}

stations_df.2 <- stations_df.1 %>%
  extract_constant_raster_values(brick(swns_raster))

stations_df.3 <- stations_df.2 %>%
filter(!(is.na(swns)) | (stationid %in% list('10859','31829','43406'))) %>%
  mutate(date_time = as.Date(date_time)) %>%
  dplyr::select(-swns)

stations_sp <- stations_df.3 %>% filter(date_time==max(date_time))
coordinates(stations_sp) = ~ EASTING + NORTHING
#usethis::use_data(stations_sp,overwrite=TRUE)
#usethis::use_data(stations_df,overwrite=TRUE)
```


I downloaded all the stations in swns from climatedata.ca (apr 2012 - nov 2016)
```{r}
eccc_df.1  <- read.csv('f:\\data\\climate_daily_edit.csv') %>%
  dplyr::select(stationid=CLIMATE_ID,
                date_time=LOCAL_DATE,
                temp_min=MIN_TEMPER,
                temp_max=MAX_TEMPER,
                EASTING,
                NORTHING)
eccc_df.2 <- eccc_df.1 %>%
  mutate(date_time = as.Date(date_time)) %>%
  mutate(stationid = as.character(stationid)) %>%
  mutate(temp_mean = (temp_min + temp_max)/2) %>%

  
  filter(between(month(date_time),4,11)) 
  
 
stations_df.4 <- stations_df.3 %>%
  bind_rows(eccc_df.2)  
```

```{r}
east_north_lookup_df.1 <- stations_df.4 %>% 
  dplyr::select(stationid,EASTING,NORTHING) %>%
  distinct()

#write.csv(east_north_lookup_df.1,'f:\\data\\stations_unique.csv')
```

```{r}
ecodist <- raster('f:\\data\\swns_ecodists_500m.tif')
names(ecodist) <- 'ecodist'
```


```{r}
ecodist_lookup_df.1 <- read.csv('f:\\data\\stations_unique_edit.csv') %>%
  dplyr::select(stationid,EASTING,NORTHING) %>%
  extract_constant_raster_values(brick(ecodist)) %>%
  mutate(ecodist=ifelse(is.na(ecodist),780,ecodist)) %>%
  mutate(ecodist=ifelse(ecodist==0,780,ecodist)) %>%
  dplyr::select(-c(EASTING,NORTHING))
```


```{r}
stations_df.5 <- stations_df.4 %>% 
  dplyr::select(stationid,date_time)%>%
  tidyr::complete(date_time = seq(ymd('2012-04-01'),
                           ymd('2016-11-30'),
                           by='day'),
                  stationid)  %>%
  left_join(east_north_lookup_df.1,by=c('stationid')) %>%
  left_join(stations_df.4 %>% 
              dplyr::select(stationid,date_time,temp_mean),
            by=c('stationid','date_time')) %>%
  left_join(ecodist_lookup_df.1,by='stationid')%>%
  extract_constant_raster_values(rasters_brick) %>%
  filter(between(year(date_time),2012,2016) &
           between(month(date_time),4,11)) %>%
  add_gdd_columns(list(0,5,10))%>% 
  dplyr::filter(stationid!='S100') %>% # 2012
  dplyr::filter(stationid!='S160') %>% # 2012, early in season/cold
  dplyr::filter(stationid!='S20')  %>% #2012
  dplyr::filter(stationid != 'S60') %>% #2012
  dplyr::filter(stationid != 'S80') %>% #2012
  dplyr::filter(stationid != 'CL1')


```



```{r}
model_stations_df.1 <- stations_df.5 %>% 
  filter(stationid %in% c(nscc_stations_list,'6354','47187')) 
model_stations_list <- model_stations_df.1$stationid %>% unique()

validation_stations_df.1 <- stations_df.5 %>%
  filter(!(stationid %in% model_stations_list)) 

validation_stations_list <- validation_stations_df.1$stationid %>% unique()

validation_stations_unique_df.1 <- validation_stations_df.1 %>% 
  dplyr::select(stationid, EASTING, NORTHING) %>% 
  distinct()
#write.csv(validation_stations_unique,'f:\\data\\validation_stations_unique.csv')
```


