---
title: "GDD10 Accumulated Monthly"
author: "Dana Melamed"
date: "`r Sys.Date()`"
output: html_document
---

Accumulate gdd10 from the beginning to end of each month, and apply the model.

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE) 
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.align = 'center')
knitr::opts_chunk$set(fig.width = 9)
knitr::opts_chunk$set(fig.height = 7)
library(swnsmodelr)
par(mfrow=c(2,2))
```


```{r}
# Prepare the data
# Make a list of input rasters
in_folder <- 'f:\\data\\rasters\\input_rasters\\'
raster_names <- list('dem700m','cp700m','east700m','north700m','tpi5000m700m',
                     'asp700m','slp700m')
ext = '.tif'
rasters_list <- lapply(X=paste0(in_folder,raster_names,ext),FUN=raster::raster)

#transform
rasters_list[[2]]<-rasters_list[[2]]^0.5
names(rasters_list[[2]]) <- 'cp700m'
rasters_list[[6]] <- rasters_list[[7]]*cos(rasters_list[[6]])
names(rasters_list[[6]]) <- 'asp700m'

# brick rasters
rasters_brick2 <- raster::brick(rasters_list)

# extract rasters to dataframe
stations_df <- swns_stations_df %>% dplyr::select(date_time,
                                           stationid,
                                           EASTING,
                                           NORTHING,
                                           temp_min,
                                           temp_max)
df_in <- stations_df %>% 
  dplyr::select(stationid,temp_min,temp_max,EASTING,NORTHING,date_time) %>%
  extract_constant_raster_values(rasters_list) %>% add_date_columns()
```


Create dataframe for each year
```{r}

# calculate gdd10 in dataframe
df <- df_in %>% add_date_columns() %>%
 # select(stationid,temp_min,temp_max,date_time)%>%
  mutate(temp_mean=(temp_min+temp_max)/2)%>%
  dplyr::filter(stationid %in% nscc_stations_list |
                  stationid == '47187' |
                  stationid == '6354')%>%
  dplyr::filter(stationid!='S100') %>% # 2012
  dplyr::filter(stationid!='S160') %>% # 2012, early in season/cold
  dplyr::filter(stationid!='S20')  %>% #2012
  dplyr::filter(stationid != 'S60') %>% #2012
  dplyr::filter(stationid != 'S80') %>% #2012
  dplyr::filter(stationid != 'CL1') %>%
  mutate(gdd10_daily=ifelse(temp_mean>10,temp_mean-10,0)) %>%
  group_by(year,month,stationid) %>%
  mutate(gdd10 = sum(gdd10_daily, na.rm = TRUE))

df_12 <- df %>% dplyr::filter(year=='2012'&between(month,4,11)) %>%
  group_by(month)%>%
  filter(yday==max(yday))

df_13 <- df %>% dplyr::filter(year=='2013'&between(month,4,11))  %>%
  group_by(month)%>%
  filter(yday==max(yday))

df_14 <- df %>% dplyr::filter(year=='2014'&between(month,4,11))  %>%
  group_by(month)%>%
  filter(yday==max(yday))

df_15 <- df %>% dplyr::filter(year=='2015'&between(month,4,11))  %>%
  group_by(month)%>%
  filter(yday==max(yday))

df_16 <- df %>% dplyr::filter(year=='2016'&between(month,4,11))  %>%
  group_by(month)%>%
  filter(yday==max(yday))
```

Model for each month of a year.
2012
```{r}
months <- df_12$month %>% unique()

m_list <- list()
c = 1
for(month in months){
  df_month <- df_12 %>% dplyr::filter(month== !!month)
  m_list[[c]] <- gam(gdd10~s(dem700m,k=30,bs='cr')+s(cp700m,k=5,bs='cr')+s(east700m,north700m,k=20),data=df_month,method='REML',family=gaussian())
  c <- c+1

}
gam_rasters <- list()
j <- 1
for(m in m_list){
  gam_rasters[[j]] <- raster::predict(rasters_brick2,m)
  plot(gam_rasters[[j]], main=m$formula, col=rev(rainbow(100)[1:70]))
  points(swns_stations_sp)
  par(mfrow=c(2,2))
  plot.gam(m, residuals = TRUE, pch = 1, cex = 1, shift = coef(m)[1])
  par(mfrow=c(1,1))
  j <- j + 1
}
sum_raster_brick <- brick(gam_rasters)
sum_raster <- raster::calc(sum_raster_brick, sum)
plot(sum_raster, main=m$formula, col=rev(rainbow(100)[1:70]))
```

2013
```{r}
months <- df_13$month %>% unique()

m_list <- list()
c = 1
for(month in months){
  df_month <- df_13 %>% dplyr::filter(month== !!month)
  m_list[[c]] <- gam(gdd10~s(dem700m,k=30,bs='cr')+s(cp700m,k=5,bs='cr')+s(east700m,north700m,k=20),data=df_month,method='REML',family=gaussian())
  c <- c+1

}
gam_rasters <- list()
j <- 1
for(m in m_list){
  gam_rasters[[j]] <- raster::predict(rasters_brick2,m)
  plot(gam_rasters[[j]], main=m$formula, col=rev(rainbow(100)[1:70]))
  points(swns_stations_sp)
  par(mfrow=c(2,2))
  plot.gam(m, residuals = TRUE, pch = 1, cex = 1, shift = coef(m)[1])
  par(mfrow=c(1,1))
  j <- j + 1
}
sum_raster_brick <- brick(gam_rasters)
sum_raster <- raster::calc(sum_raster_brick, sum)
plot(sum_raster, main=m$formula, col=rev(rainbow(100)[1:70]))
```

2014
```{r}
months <- df_14$month %>% unique()

m_list <- list()
c = 1
for(month in months){
  df_month <- df_14 %>% dplyr::filter(month== !!month)
  m_list[[c]] <- gam(gdd10~s(dem700m,k=30,bs='cr')+s(cp700m,k=5,bs='cr')+s(east700m,north700m,k=20),data=df_month,method='REML',family=gaussian())
  c <- c+1

}
gam_rasters <- list()
j <- 1
for(m in m_list){
  gam_rasters[[j]] <- raster::predict(rasters_brick2,m)
  plot(gam_rasters[[j]], main=m$formula, col=rev(rainbow(100)[1:70]))
  points(swns_stations_sp)
  par(mfrow=c(2,2))
  plot.gam(m, residuals = TRUE, pch = 1, cex = 1, shift = coef(m)[1])
  par(mfrow=c(1,1))
  j <- j + 1
}
sum_raster_brick <- brick(gam_rasters)
sum_raster <- raster::calc(sum_raster_brick, sum)
plot(sum_raster, main=m$formula, col=rev(rainbow(100)[1:70]))
```

2015
```{r}
months <- df_15$month %>% unique()

m_list <- list()
c = 1
for(month in months){
  df_month <- df_15 %>% dplyr::filter(month== !!month)
  m_list[[c]] <- gam(gdd10~s(dem700m,k=30,bs='cr')+s(cp700m,k=5,bs='cr')+s(east700m,north700m,k=20),data=df_month,method='REML',family=gaussian())
  c <- c+1

}
gam_rasters <- list()
j <- 1
for(m in m_list){
  gam_rasters[[j]] <- raster::predict(rasters_brick2,m)
  plot(gam_rasters[[j]], main=m$formula, col=rev(rainbow(100)[1:70]))
  points(swns_stations_sp)
  par(mfrow=c(2,2))
  plot.gam(m, residuals = TRUE, pch = 1, cex = 1, shift = coef(m)[1])
  par(mfrow=c(1,1))
  j <- j + 1
}
sum_raster_brick <- brick(gam_rasters)
sum_raster <- raster::calc(sum_raster_brick, sum)
plot(sum_raster, main=m$formula, col=rev(rainbow(100)[1:70]))
```

2016
```{r}
months <- df_16$month %>% unique()

m_list <- list()
c = 1
for(month in months){
  df_month <- df_16 %>% dplyr::filter(month== !!month)
  m_list[[c]] <- gam(gdd10~s(dem700m,k=30,bs='cr')+s(cp700m,k=5,bs='cr')+s(east700m,north700m,k=20),data=df_month,method='REML',family=gaussian())
  c <- c+1

}
gam_rasters <- list()
j <- 1
month_names <- c('April','May','June','July','August','September','October','November')
for(m in m_list){
  gam_rasters[[j]] <- raster::predict(rasters_brick2,m)
  plot(gam_rasters[[j]], main=month_names[[j]], col=rev(rainbow(100)[1:70]))
  points(swns_stations_sp)
  par(mfrow=c(2,2))
  plot.gam(m, residuals = TRUE, pch = 1, cex = 1, shift = coef(m)[1])
  par(mfrow=c(1,1))
  j <- j + 1
}
sum_raster_brick <- brick(gam_rasters)
sum_raster <- raster::calc(sum_raster_brick, sum)
plot(sum_raster, main=m$formula, col=rev(rainbow(100)[1:70]))
```



