---
title: "Untitled"
author: "Dana Melamed"
date: "August 7, 2018"
output: word_document
---

```{r warning=FALSE, echo=FALSE, message = FALSE}
library(swnsmodelr)
library(ggplot2)
```



```{r warning=FALSE, message = FALSE, echo = FALSE}
# Plot GDD maps for report

# Plot monthly accumulated report

# GDD0 at monthly intervals
gdd0_raster_df <- make_temporal_raster_df(file.path("E:","Daily","Daily_GDD0"),
                                         start_date = ymd('2012-04-01'),
                                         end_date   = ymd('2017-11-30'),
                                         date_chars = c(6,-4),
                                         date_format = "%Y-%m-%d") %>% arrange(date_time)
gdd5_raster_df <- make_temporal_raster_df(file.path("E:","Daily","Daily_GDD5"),
                                          start_date = ymd('2012-04-01'),
                                          end_date   = ymd('2017-11-30'),
                                          date_chars = c(6,-4),
                                          date_format = "%Y-%m-%d") %>% arrange(date_time)
gdd10_raster_df <- make_temporal_raster_df(file.path("E:","Daily","Daily_GDD10"),
                                          start_date = ymd('2012-04-01'),
                                          end_date   = ymd('2017-11-30'),
                                          date_chars = c(7,-4),
                                          date_format = "%Y-%m-%d") %>% arrange(date_time)

library(RColorBrewer)

# Classic palette BuPu, with 4 colors
coul = brewer.pal(4, "Spectral") 

# I can add more tones to this palette :
coul = colorRampPalette(coul)(100)
```


```{r warning = FALSE, message = FALSE, echo = FALSE, fig.height = 10, fig.width= 10, eval = FALSE}
# plot for all months, all years
par(mfrow = c(2,2), xpd = NA)
for(i in seq_along(gdd0_raster_df[[1]])){
  date_now <- gdd0_raster_df$date_time[[i]]
  month_now <- month(date_now)
  
  if(day(date_now) == days_in_month(month_now)){
    raster_now <- gdd0_raster_df$path_field[[i]] %>% raster
    plot(raster_now, zlim = c(0,3300),
         col = rev(coul),
         main = paste0("GDD0: ",date_now))
  }
  
}

par(mfrow = c(2,2), xpd = NA)
for(i in seq_along(gdd5_raster_df[[1]])){
  date_now <- gdd0_raster_df$date_time[[i]]
  month_now <- month(date_now)
  
  if(day(date_now) == days_in_month(month_now)){
    raster_now <- gdd5_raster_df$path_field[[i]] %>% raster
    plot(raster_now, zlim = c(0,2300),
         col = rev(coul),
         main =  paste0("GDD5: ",date_now))
  }
  
}

par(mfrow = c(2,2), xpd = NA)
for(i in seq_along(gdd10_raster_df[[1]])){
  date_now <- gdd10_raster_df$date_time[[i]]
  month_now <- month(date_now)
  
  if(day(date_now) == days_in_month(month_now)){
    raster_now <- gdd10_raster_df$path_field[[i]] %>% raster
    plot(raster_now, zlim = c(0,1300),
         col = rev(coul),
         main =  paste0("GDD10: ",date_now))
  }
  
}

```



```{r warning = FALSE, message = FALSE, echo = FALSE, fig.height = 10, fig.width= 10, eval = FALSE}
# plot for end of year, compare years
par(mfrow = c(2,2), xpd = NA)
for(i in seq_along(gdd0_raster_df[[1]])){
  date_now <- gdd0_raster_df$date_time[[i]]
  month_now <- month(date_now)
  
  if(day(date_now) == days_in_month(month_now) & month_now == 11){
    raster_now <- gdd0_raster_df$path_field[[i]] %>% raster
    plot(raster_now, zlim = c(2600,3300),
         col = rev(coul),
         main = paste0("GDD0: ",date_now))
  }
  
}

par(mfrow = c(2,2), xpd = NA)
for(i in seq_along(gdd5_raster_df[[1]])){
  date_now <- gdd0_raster_df$date_time[[i]]
  month_now <- month(date_now)
  
  if(day(date_now) == days_in_month(month_now) & month_now == 11){
    raster_now <- gdd5_raster_df$path_field[[i]] %>% raster
    plot(raster_now, zlim = c(1500,2300),
         col = rev(coul),
         main =  paste0("GDD5: ",date_now))
  }
  
}

par(mfrow = c(2,2), xpd = NA)
for(i in seq_along(gdd10_raster_df[[1]])){
  date_now <- gdd10_raster_df$date_time[[i]]
  month_now <- month(date_now)
  
  if(day(date_now) == days_in_month(month_now) & month_now == 11){
    raster_now <- gdd10_raster_df$path_field[[i]] %>% raster
    plot(raster_now, zlim = c(600,1300),
         col = rev(coul),
         main =  paste0("GDD10: ",date_now))
  }
  
}

```


```{r warning = FALSE, message = FALSE, echo = FALSE, fig.height = 10, fig.width= 10}
# plot six year averages
raster_to_avg <- list()
j <- 1
for(i in seq_along(gdd0_raster_df[[1]])){
  date_now <- gdd0_raster_df$date_time[[i]]
  month_now <- month(date_now)
  
  if(day(date_now) == days_in_month(month_now) & month_now == 11){
    
    raster_now <- gdd0_raster_df$path_field[[i]] %>% raster
    raster_to_avg[[j]] <- raster_now
    j <- j + 1
  }

}

  avg_raster <- mean(raster_to_avg[[1]],
                     raster_to_avg[[2]],
                     raster_to_avg[[3]],
                     raster_to_avg[[4]],
                     raster_to_avg[[5]],
                     raster_to_avg[[6]])
  plot(avg_raster, zlim = c(2600,3200),
         col = rev(coul),
         main = paste0("GDD0: Six-Year Average"))

  j <- 1
for(i in seq_along(gdd5_raster_df[[1]])){
  date_now <- gdd0_raster_df$date_time[[i]]
  month_now <- month(date_now)
  
  if(day(date_now) == days_in_month(month_now) & month_now == 11){
    
    raster_now <- gdd5_raster_df$path_field[[i]] %>% raster
    raster_to_avg[[j]] <- raster_now
    j <- j + 1
  }

}

  avg_raster <- mean(raster_to_avg[[1]],
                     raster_to_avg[[2]],
                     raster_to_avg[[3]],
                     raster_to_avg[[4]],
                     raster_to_avg[[5]],
                     raster_to_avg[[6]])
  plot(avg_raster, zlim = c(1500,2100),
         col = rev(coul),
         main = paste0("GDD5: Six-Year Average"))
  
j <- 1
for(i in seq_along(gdd10_raster_df[[1]])){
  date_now <- gdd0_raster_df$date_time[[i]]
  month_now <- month(date_now)
  
  if(day(date_now) == days_in_month(month_now) & month_now == 11){
    
    raster_now <- gdd10_raster_df$path_field[[i]] %>% raster
    raster_to_avg[[j]] <- raster_now
    j <- j + 1
  }

}

  avg_raster <- mean(raster_to_avg[[1]],
                     raster_to_avg[[2]],
                     raster_to_avg[[3]],
                     raster_to_avg[[4]],
                     raster_to_avg[[5]],
                     raster_to_avg[[6]])
  plot(avg_raster, zlim = c(600,1150),
         col = rev(coul),
         main = paste0("GDD10: Six-Year Average"))

```